{{- if and .Values.bbtests.enabled .Values.networkPolicies.enabled .Values.minio.enabled .Values.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-minio-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
    ports:
    - port: 9000
      protocol: TCP
  podSelector:
    matchLabels:
      app: minio
  policyTypes:
  - Ingress
{{- end }}
