{{- if .Values.networkPolicies.enabled  }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grafana-thanos-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
    ports:
    - port: {{ .Values.receive.service.ports.http }}
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: query
  policyTypes:
  - Ingress
{{- end }}
