{{ if and .Values.istio.enabled .Values.networkPolicies.enabled .Values.sso.enabled }}
{{- if (eq .Values.istio.injection "disabled") -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-authservice-thanos
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: thanos
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: authservice
      podSelector:
        matchLabels:
          app.kubernetes.io/name: haproxy
    ports:
      - port: 10902
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-authservice-thanos
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: thanos
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 10003
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: authservice
      namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: authservice
{{- end }}
{{- end }}
