{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.minioOperator.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: thanos-minio-operator-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      v1.min.io/tenant: thanos-minio
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.minioOperator.namespaces }}
        principals: {{ .Values.istio.hardened.minioOperator.principals }}
{{- end }}
