{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.thanos.enabled .Values.minio.enabled -}}
{{- range .Values.istio.thanos.gateways -}}
{{- $gatewayParts := split "/" . }}
{{- $namespace := $gatewayParts._0 }}
{{- $name := $gatewayParts._1 }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "minio-{{ $name }}-ingressgateway-authz-policy"
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "minio.labels" . | nindent 6 }} 
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - {{ $namespace }}
        principals:
        - "cluster.local/ns/{{ $namespace }}/sa/{{ $name }}-ingressgateway-service-account"
---
{{ end -}}
{{- end }}