{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.prometheus.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: thanos-query-prometheus-authz-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
        app.kubernetes.io/component: query
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.prometheus.namespaces }}
        principals: {{ .Values.istio.hardened.prometheus.principals }}
{{- end }}