{{- if include "thanos.shouldDeployUpgradeResources" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.upgradeJob.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
{{- end }}