{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if and (include "common.capabilities.psp.supported" .) $query.enabled $query.pspEnabled $query.rbac.create }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}-query
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: query
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  kind: ClusterRole
  name: {{ include "common.names.fullname" . }}-query
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "thanos.serviceAccountName" (dict "component" "query" "context" $) }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
