{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if (include "thanos.query.createSDConfigmap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-query-sd-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: query
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  servicediscovery.yml: |-
    {{- include "common.tplvalues.render" (dict "value" $query.sdConfig "context" $) | nindent 4 }}
{{ end }}
